version: '3.0'
services:
  web:
    image: pruizca/hugo
    container_name: personal_website
    hostname: website
    ports:
    - "1313:1313"
    volumes:
    - ./:/site
    environment:
    - DOMAIN=${DOMAIN_NAME}

