version: '2.0'
services:
  web:
    build: .
    ports:
    - "1313:1313"
    volumes:
    - ~/pedroruiz.xyz:/site
    hostname: website

    networks:
    - homeserver

networks:
  homeserver:
    external:
      name: homeserver

